### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by ZachAndrews98** [zbzoll/zbzoll.github.io#13]
Looks like you're off to a good start, however, there are a few things that I noticed you could change.
I would change "cannot" in your title to "can't" and capitalize every word not just a few. 
You're TL;DR poses a question and then answers it right away.
Make "test" plural and remove the comma after "ACT". 
Capitalize "i" in the last sentence. 
Remove "and went through it too".
Add <small> tags to the beginnings of your Flickr image credits.

**Comment by zbzoll** [comment]
ok thanks will work on all these topics

**Comment by ZachAndrews98** [comment]
Looks good but there are a few changes you should make.
Remove "and went through it too".
Make "test" plural and remove the comma after "ACT".
Remove "rather" from the 6th sentence, second paragraph and replace it with "a".
Remove "an" from the first sentence, third paragraph.
Fix "essays’" (remove the ' from the end).
Make administrators singular 4th sentence, third paragraph.
You need to add a naysayer to your article.
Add tags to the beginnings of your Flickr image credits.

**Comment by zbzoll** [comment]
thanks I got it done
